server:
  port: 443
  ssl:
    key-store: www.llbbk.xyz.jks
    key-store-password: z8331b617r094
    key-store-type: JKS
    key-alias: www.llbbk.xyz
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址 ,外部服务器，写IP地址
    host: 49.235.97.129
    # Redis服务器连接端口
    port: 6379
    spring:
      redis:
        # Redis服务器连接密码（默认为空）
        password:
    jedis:
      pool:
        max-idle: 200
        # 连接池最大连接数（使用负值表示没有限制）
    timeout: 300
  data:
    mongodb:
      uri: mongodb://localhost:27017/remarks
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  #  thymeleaf:
  #    cache: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.235.97.129:3306/rent?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Llb_980820
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  # 跳转到/WEB-INF/下的.html页面
  freemarker:
    template-loader-path: /WEB-INF/
    suffix: .html

mybatis:
  type-aliases-package: com.elife.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql